version: "3.8"

services:
  api:
    build: ./server
    ports:
      - "5000:5000"
    env_file: .env
    depends_on:
      - ai-service
    environment:
      AI_SERVICE_URL: http://ai-service:8001

  ai-service:
    build: ./ai-service
    ports:
      - "8001:8001"
    env_file: .env
